[package]
name = "yagit"
version = "0.1.0"
edition = "2021"
description = "Yet another static site generator for Git"

[dependencies]
git2 = "0.20.0"
libc = "0.2.170"
pulldown-cmark = { version = "0.13.0", features = ["simd"] }
static-toml = "1.3.0"

[profile.release]
debug = true
