[output]
path                = "/var/www/git"
tree_subdir         = "tree"
blob_subdir         = "blob"
commit_subdir       = "commit"
private_output_root = "private/"

[git]
store_path         = "/var/git/public"  # path to the public  repo store
private_store_path = "/var/git/private" # path to the private repo store
store_owner        = "Pablo"
user               = "git"
